language: EN

lang:
  EN:
    needop: You have to be OP to use this command!
    onlyingame: That command is only for in-game players!
    usage: 'Usage: /inv <player>'
    enderusage: 'Usage: /enderinv <player>'
    playernotonline: That player is not online!
    lookedinyourinv: §f is looking in your inventory!
  NL:
    needop: Je moet OP zijn voor dit commando!
    onlyingame: Dat commando is alleen voor in-game spelers!
    usage: 'Doe: /inv <player>'
    enderusage: 'Doe: /enderinv <player>'
    playernotonline: Die speler is niet online!
    lookedinyourinv: §f kijkt in je inventaris!
  FR:
    needop: Vous devez être OP pour cette commande!
    onlyingame: Cette commande est seulement pour les joueurs!
    usage: 'Faire: /inv <player>'
    enderusage: 'Faire: /enderinv <player>'
    playernotonline: Ce joueurs n'est pas en ligne!
    lookedinyourinv: §f regarde dans votre inventaire!
  DE:
    needop: Du musst OP sein um diesen Befehl benutzen zu können!
    onlyingame: Dieser Befehl ist nur für InGame Spieler!
    usage: 'Benutzung: /inv <Spieler>'
    enderusage: 'Benutzung: /enderinv <player>'
    playernotonline: Der Spieler ist nicht online!
    lookedinyourinv: §f schaut sich dein Inventar an!
  DK:
    needop: Du skal være OP for at bruge denne komando!
    onlyingame: Denne komando er kun for in-game spillere!
    usage: 'Usage: /inv <spiller>'
    enderusage: 'Usage: /enderinv <spiller>'
    playernotonline: Denne spiller er ikke online!
    lookedinyourinv: §f kigger i din inventory!